### PR TITLE
use Turing through imports

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by Vaibhavdixit02** [comment]
Will require new release of AdvancedHMC https://github.com/TuringLang/AdvancedHMC.jl/pull/160, once it's in this should be good to go. Works for me locally.

**Comment by xukai92** [comment]
The new release is there.

**Comment by Vaibhavdixit02** [comment]
Thanks @xukai92!

**Comment by ChrisRackauckas** [comment]
@xukai92 can we get some help figuring out what Turing is trying to iterate?

**Comment by xukai92** [comment]
Do you mean why we do this DynamicPPL thing?

**Comment by Vaibhavdixit02** [comment]
@ChrisRackauckas that happens because https://github.com/TuringLang/Turing.jl/blob/master/src/inference/Inference.jl#L856's types, the `MvNormal` is `<:` both `Distribution` and `MultivariateDistribution`, but the `MultivariateDistribution` method does not accept `AbstractArray` type, so when you don't matrixize in the `dot_tilde` call here, it can't iterate. On changing it though, I am encountering another error which I can't understand https://travis-ci.org/JuliaDiffEq/DiffEqBayes.jl/jobs/635608371?utm_medium=notification&utm_source=github_status

**Comment by xukai92** [comment]
It's might be related to what @mohamed82008 is trying to fix.

**Comment by mohamed82008** [comment]
Yes that looks related to https://github.com/TuringLang/Turing.jl/pull/1043. I will take a look next week. Please open an issue in Turing to track it, happy to investigate when I get some time.

**Pull request closed without merging**
