### PR TITLE
Update Turing inference

### PR DESCRIPTION
**Pull request by xukai92**
Resolve https://github.com/JuliaDiffEq/DiffEqBayes.jl/issues/46

### CODE REVIEW

**Comment by xukai92** [comment]
My Turing.jl PR was just merged and I made a new release. But it seems that the new version cannot be fetched. Should I do something else or it's a problem of time?

**Comment by ChrisRackauckas** [comment]
A tag was never sent to METADATA: https://github.com/JuliaLang/METADATA.jl/pulls?utf8=%E2%9C%93&q=Turing

**Comment by xukai92** [comment]
It is because of the change of URL?

**Comment by ChrisRackauckas** [comment]
Attobot probably wasn't enabled in the new org.

**Comment by xukai92** [comment]
It's in the METADATA PR list now. @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Thanks!

**Pull request merged**
