### PR TITLE
Added ABC inference using ApproxBayes.jl

### PR DESCRIPTION
**Pull request by marcjwilliams1**
Initial version of abc_inference which uses the ApproxBayes package to do Approximate Bayesian Computation inference.

### CODE REVIEW

**Comment by marcjwilliams1** [comment]
Sorry, I've managed to make a new PR rather than add it here. How do I do that properly? I did `PkgDev.submit("DiffEqBayes")` again

**Comment by ChrisRackauckas** [comment]
`PkgDev.submit` is not for submitting PRs to repositories. It's for submitting tags to METADATA.jl. Here's a video that shows how to do this package dev stuff:

https://www.youtube.com/watch?v=tx8DRc7_c9I

**Comment by marcjwilliams1** [comment]
Thanks, I'll take a look at the video. 

I followed what was outlined in the code changes section in the julia docs: https://docs.julialang.org/en/stable/manual/packages/#Packages-1

**Comment by ChrisRackauckas** [comment]
That page is for the package manager and submitting packages to the METADATA.jl registry, but not for actually working on packages themselves.

**Comment by marcjwilliams1** [comment]
anyway, thanks for the video, I'll follow that procedure in future

**Comment by ChrisRackauckas** [comment]
>The last line will present you with a link to submit a pull request to incorporate your changes.

To incorporate your changes into METADATA.jl. 

https://github.com/JuliaLang/METADATA.jl

**Pull request closed without merging**
