### PR TITLE
Update stan_inference.jl

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Hmm it didn't seem to fix the error @goedman .

**Comment by goedman** [comment]
No, still seems to indicate stanc handles _s in a special way. I’ll get this confirmed with Bob and at the same time I’m studying ParameterizedFunctions. Hats off for ParameterizedFunctions!

**Comment by ChrisRackauckas** [comment]
I can just get rid of all `_`s and make the prefix `internalvarrr` or something silly like that to make sure it doesn't have namspacing issues. Would that fix it?

**Comment by goedman** [comment]
Reverting the last 4 commits on ParameterizedFunctions (back where things were a few months ago) works and generates this Stan program:

```
functions {
    real[] sho(real t,real[] u,real[] theta,real[] x_r,int[] x_i) {
      real du[3];
          du[1] = 10.0 * (u[2] - u[1]);    du[2] = u[1] * (28.0 - u[3]) - u[2];    du[3] = u[1] * u[2] - theta[1] * u[3];
      return du;
      }
    }
  data {
    real u0[3];
    int<lower=1> T;
    real u[T,3];
    real t0;
    real ts[T];
    real reltol;
    real abstol;
    int maxiter;
  }
  transformed data {
    real x_r[0];
    int x_i[0];
  }
  parameters {
    vector<lower=0>[3] sigma;
    real theta[1];
  }
  model{
    real u_hat[T,3];
    sigma ~ inv_gamma(2, 3);
    theta[1] ~ normal(2.6666, 1.0) ; 
    u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, reltol, abstol, maxiter);
    for (t in 1:T){
      u[t] ~ normal(u_hat[t], sigma);
      }
  }
```

I expect the right hand side u[.] values come from the data{...} section.

The current version (with updated declaration and return statements) generates:

```
functions {
    real[] sho(real t,real[] u,real[] theta,real[] x_r,int[] x_i) {
      real internal_var___du[3];
          internal_var___du[1] = 10.0 * (internal_var___u[2] - internal_var___u[1]);    internal_var___du[2] = internal_var___u[1] * (28.0 - internal_var___u[3]) - internal_var___u[2];    internal_var___du[3] = internal_var___u[1] * internal_var___u[2] - theta[1] * internal_var___u[3];
      return internal_var___du;
      }
    }
  data {
    real u0[3];
    int<lower=1> T;
    real u[T,3];
    real t0;
    real ts[T];
    real reltol;
    real abstol;
    int maxiter;
  }
  transformed data {
    real x_r[0];
    int x_i[0];
  }
  parameters {
    vector<lower=0>[3] sigma;
    real theta[1];
  }
  model{
    real u_hat[T,3];
    sigma ~ inv_gamma(2, 3);
    theta[1] ~ normal(2.6666, 1.0) ; 
    u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, reltol, abstol, maxiter);
    for (t in 1:T){
      u[t] ~ normal(u_hat[t], sigma);
      }
  }
```

and points to:

```

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

variable "internal_var___u" does not exist.
  error in '/Users/rob/.julia/v0.6/Stan/Examples/OtherExamples/DiffEqBayes/Lorenz_02/tmp/parameter_estimation_model.stan' at line 4, column 58
  -------------------------------------------------
     2:     real[] sho(real t,real[] u,real[] theta,real[] x_r,int[] x_i) {
     3:       real internal_var___du[3];
     4:           internal_var___du[1] = 10.0 * (internal_var___u[2] - internal_var___u[1]);    internal_var___du[2] = internal_var___u[1] * (28.0 - internal_var___u[3]) - internal_var___u[2];    internal_var___du[3] = internal_var___u[1] * internal_var___u[2] - theta[1] * internal_var___u[3];
                                                                 ^
     5:       return internal_var___du;
  -------------------------------------------------


make: *** [/Users/rob/.julia/v0.6/Stan/Examples/OtherExamples/DiffEqBayes/Lorenz_02/tmp/parameter_estimation_model.hpp] Error 253
```

I think it can no longer resolve the right hand side ```internal_var___u[.]``` values.

And indeed, if I adapt my version of bayesian_inference it generates:

```
functions {
    real[] sho(real t,real[] u,real[] theta,real[] x_r,int[] x_i) {
      real internal_var___du[3];
      internal_var___du[1] = 10.0 * (u[2] - u[1]);
      internal_var___du[2] = u[1] * (28.0 - u[3]) - u[2];
      internal_var___du[3] = u[1] * u[2] - theta[1] * u[3];
      return internal_var___du;
      }
    }
  data {
    real u0[3];
    int<lower=1> T;
    real u[T,3];
    real t0;
    real ts[T];
    real reltol;
    real abstol;
    int maxiter;
  }
  transformed data {
    real x_r[0];
    int x_i[0];
  }
  parameters {
    vector<lower=0>[3] sigma;
    real theta[1];
  }
  model{
    real u_hat[T,3];
    sigma ~ inv_gamma(2, 3);
    theta[1] ~ normal(2.6666, 1.0) ; 
    u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, reltol, abstol, maxiter);
    for (t in 1:T){
      u[t] ~ normal(u_hat[t], sigma);
      }
  }
```

and kind of works again. Kind of because I remain suspicious of the plots produced.

If it would help I can push this example to Stan.jl.

**Comment by ChrisRackauckas** [comment]
```julia
functions {
    real[] sho(real t,real[] u,real[] theta,real[] x_r,int[] x_i) {
      real internal_var___du[3];
          internal_var___du[1] = 10.0 * (internal_var___u[2] - internal_var___u[1]);    internal_var___du[2] = internal_var___u[1] * (28.0 - internal_var___u[3]) - internal_var___u[2];    internal_var___du[3] = internal_var___u[1] * internal_var___u[2] - theta[1] * internal_var___u[3];
      return internal_var___du;
      }
    }
  data {
    real u0[3];
    int<lower=1> T;
    real u[T,3];
    real t0;
    real ts[T];
    real reltol;
    real abstol;
    int maxiter;
  }
  transformed data {
    real x_r[0];
    int x_i[0];
  }
  parameters {
    vector<lower=0>[3] sigma;
    real theta[1];
  }
  model{
    real u_hat[T,3];
    sigma ~ inv_gamma(2, 3);
    theta[1] ~ normal(2.6666, 1.0) ; 
    u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, reltol, abstol, maxiter);
    for (t in 1:T){
      u[t] ~ normal(u_hat[t], sigma);
      }
  }
```

I think the issue here is we still haven't renamed everything. `sho(real t,real[] u,real[] theta,real[] x_r,int[] x_i) ` should have `internal_var___u`. I'll give that a try.

**Comment by ChrisRackauckas** [comment]
The find replace code worked on string parts which was too invasive. The new generated Stan program looks like:

```julia
julia> println(parameter_estimation_model)
functions {
  real[] sho(real t,real[] internal_var___u,real[] theta,real[] x_r,i
nt[] x_i) {
    real internal_var___du[2];
    internal_var___du[1] = theta[1] * internal_var___u[1] - internal_
var___u[1] * 1.0 * internal_var___u[2];
internal_var___du[2] = internal_var___u[2] * -3.0 + internal_var___u[
1] * 1.0 * internal_var___u[2];

    return internal_var___du;
    }
  }
data {
  real u0[2];
  int<lower=1> T;
  real internal_var___u[T,2];
  real t0;
  real ts[T];
}
transformed data {
  real x_r[0];
  int x_i[0];
}
parameters {
  vector<lower=0>[2] sigma;
  real theta[1];
}
model{
  real u_hat[T,2];
  sigma ~ inv_gamma(2, 3);
  theta[1] ~ normal(1.5, 1.0) ;
  u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, 0.001,
 0.001, 500);
  for (t in 1:T){
    u[t] ~ normal(u_hat[t], sigma);
    }
}
```

I can't test it locally but I'll see what CI generates. I think this will work.

**Comment by ChrisRackauckas** [comment]
Got it. Yup, it was just that the name change needed to happen more places.

**Comment by goedman** [comment]
Thanks Chris, it works on my system as well.

**Pull request merged**
